apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: pipeline-demo
  namespace: pipeline-demo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  promotionPolicies:
  - stageSelector:
      matchLabels:
        autopromote: "true"
    autoPromotionEnabled: true
