---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: pipeline-demo
  annotations:
    kargo.akuity.io/color: green
    kargo.akuity.io/argocd-context: '[{"name":"pipeline-demo-dev","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: pipeline-demo
  annotations:
    kargo.akuity.io/color: yellow
    kargo.akuity.io/argocd-context: '[{"name":"pipeline-demo-staging","namespace":"argocd"}]'
  labels:
    autopromote: "true"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages:
      - dev
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eu
  namespace: pipeline-demo
  annotations:
    kargo.akuity.io/color: red
    kargo.akuity.io/argocd-context: '[{"name":"pipeline-demo-prod","namespace":"argocd"}]'
  labels:
    autopromote: "true"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages:
      - staging
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-us
  namespace: pipeline-demo
  annotations:
    kargo.akuity.io/color: orange
    kargo.akuity.io/argocd-context: '[{"name":"pipeline-demo-prod","namespace":"argocd"}]'
  labels:
    autopromote: "true"
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: nginx
    sources:
      stages:
      - staging
      autoPromotionOptions:
        selectionPolicy: MatchUpstream
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
