name: Reset Demo

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reset branch
        uses: actions/checkout@v4
        with:
          ref: reset
          fetch-depth: 0

      - name: Reset main to reset branch
        run: |
          git push origin refs/heads/reset:refs/heads/main --force

      - name: Delete resources
        env:
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
          ARGOCD_OPTS: --grpc-web
          AKUITY_ORG_ID: ${{ vars.AKUITY_ORG_ID }}
          KARGO_API_TOKEN: ${{ secrets.KARGO_API_TOKEN }}
          KARGO_API_ADDRESS: ${{ vars.KARGO_API_ADDRESS }}
        run: |
          ./hack/reset-demo.sh
